# Generated by Django 3.0.1 on 2019-12-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('price0', models.IntegerField()),
                ('price1', models.IntegerField()),
                ('price2', models.IntegerField()),
                ('price3', models.IntegerField()),
                ('price4', models.IntegerField()),
                ('price5', models.IntegerField()),
                ('price6', models.IntegerField()),
                ('price7', models.IntegerField()),
            ],
        ),
    ]
