# Generated by Django 3.0.1 on 2019-12-27 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comp',
        ),
    ]
