# Generated by Django 3.0.1 on 2019-12-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_profile_comp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Apple',
            field=models.IntegerField(default=0),
        ),
    ]
