# Generated by Django 3.0.1 on 2019-12-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_profile_apple'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Alibaba',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Alphabet',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Amazon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Berkshire',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Facebook',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='JPMorgan',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Johnson',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Microsoft',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='Tencent',
            field=models.IntegerField(default=0),
        ),
    ]
