# Generated by Django 3.0.1 on 2019-12-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20191227_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Alibaba',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Alphabet',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Amazon',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Apple',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Berkshire',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Facebook',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='JPMorgan',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Johnson',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Microsoft',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Tencent',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=10000),
        ),
    ]
