# Generated by Django 3.0.1 on 2019-12-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20191227_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='price0',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price2',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price3',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price4',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price5',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price6',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='price7',
            field=models.FloatField(),
        ),
    ]
