# Generated by Django 3.0.1 on 2020-01-14 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200113_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Alibaba',
            new_name='ALPHA',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Alphabet',
            new_name='Enigma',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Amazon',
            new_name='GAAP',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Apple',
            new_name='LAXMI',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Berkshire',
            new_name='Lifepoint',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Facebook',
            new_name='Punjab',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='JPMorgan',
            new_name='RIGHT',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Johnson',
            new_name='Tec',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Microsoft',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Tencent',
        ),
    ]
