# Generated by Django 3.0.1 on 2020-01-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20200115_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price10',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='price8',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='price9',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price0',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price1',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price2',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price3',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price4',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price5',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price6',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='price7',
            field=models.FloatField(default=0),
        ),
    ]
