# Generated by Django 3.0.1 on 2020-01-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20200117_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price11',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='price12',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='price13',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='price14',
            field=models.FloatField(default=0),
        ),
    ]
