# Generated by Django 3.2.2 on 2022-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_auto_20200117_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='year',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='profile',
            name='money',
            field=models.FloatField(default=1000000),
        ),
    ]
